USE [SchoolManagement];
GO

CREATE TABLE TBLKhoa (
	MaKhoa INT PRIMARY KEY NOT NULL,
	TenKhoa NVARCHAR (255) NOT NULL
);
GO

CREATE TABLE TBLSinhVien (
	MaSV INT PRIMARY KEY NOT NULL,
	HoTen NVARCHAR (30) NOT NULL,
	MaKhoa INT NOT NULL,
	FOREIGN KEY (MaKhoa)
	REFERENCES TBLKhoa (MaKhoa),
	NamSinh VARCHAR(4),
	QueQuan NVARCHAR (50)
);
GO

CREATE TABLE TBLGiangVien (
	MaGV INT PRIMARY KEY NOT NULL,
	HoTen NVARCHAR(30) NOT NULL,
	MaKhoa INT NOT NULL,
	FOREIGN KEY (MaKhoa)
	REFERENCES TBLKhoa (MaKhoa)
);
GO